ENV_LLM_PROVIDER = "LLM_PROVIDER"
ENV_GEMINI_API_KEY = "GEMINI_API_KEY"
ENV_HF_TOKEN = "HF_TOKEN"
ENV_DEEPGRAM_API_KEY = "DEEPGRAM_API_KEY"

ENV_BACKEND = "BACKEND"
ENV_POSTGRES_DSN = "POSTGRES_DSN"
ENV_DATABASE_URL = "DATABASE_URL"
ENV_POSTGRES_HISTORY_TABLE = "POSTGRES_HISTORY_TABLE"

ENV_MAX_HISTORY_MESSAGES = "MAX_HISTORY_MESSAGES"
ENV_MIN_ANSWER_SENTENCES = "MIN_ANSWER_SENTENCES"
ENV_MIN_ANSWER_WORDS = "MIN_ANSWER_WORDS"

DEFAULT_BACKEND = "memory"
DEFAULT_POSTGRES_HISTORY_TABLE = "InterviewUserSessions"
DEFAULT_MAX_HISTORY_MESSAGES = "50"
DEFAULT_MIN_ANSWER_SENTENCES = "2"
DEFAULT_MIN_ANSWER_WORDS = "12"
